-- 색상 동의어 사전 부트스트랩 시드 (이슈 #258) — 789행, embedding 은 NULL.
--
-- ⚠️ 이 파일은 생성물이다 — 손으로 고치지 마라. `scripts/derive_color_synonym_seed.py` 로 재생성한다.
-- 정본은 `db/catalog/seed/color_synonyms.json`(같은 원천에서 파생) + 사람 검수 오버레이
-- `db/catalog/seed/color_synonyms_review.json`. 자세한 절차는 `db/catalog/seed/README.md`.
-- 여기서는 행만 만든다(embedding NULL) — 임베딩은 2단계 배치
-- (`app.pipelines.color_synonym_seed.seed_from_file`)가 채운다(04_categories_seed.sql 관례 그대로).
--
-- docker-entrypoint-initdb.d 는 컨테이너가 "완전히 새로" 뜰 때(빈 볼륨) 1회만 실행한다 —
-- 이미 만들어진 컨테이너의 볼륨에는 자동 반영되지 않는다. 기존 DB 에는 이렇게 수동 적용한다:
-- docker exec -i jarvis-ai-pg-catalog-1 psql -U jarvis -d catalog < db/catalog/init/05_color_synonyms_seed.sql
-- 재적재 시에는 검수로 승격된 status/canonical 등이 기존 행에도 반영돼야 하므로 충돌 행을
-- 정본 값으로 갱신한다. embedding/embedding_model 은 2단계 배치 소유이므로 절대 갱신하지 않는다.

INSERT INTO color_synonyms (term, canonical, status, provenance, doc_count) VALUES
    ('001 코랄스튜디오', NULL, 'rejected', 'human', 1),
    ('001 핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('001 핑크(라이트 핑크)', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('002 로즈커넥트', NULL, 'rejected', 'human', 1),
    ('003 뮤트라이브러리', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('004 코랄', NULL, 'rejected', 'human', 1),
    ('004 핑크페어링', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('007 라즈베리', NULL, 'rejected', 'human', 1),
    ('008 라떼는선임', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('008 울트라 핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('01 달빛물방울', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('01 로즈핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('01 핑크 더비', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('01. 실버 프리즘', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('012 로즈우드', NULL, 'rejected', 'human', 1),
    ('014 영원한모브를약속해줘', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('015 체리', NULL, 'rejected', 'human', 1),
    ('02 레드 플레이버', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('02 말랑반죽', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('02 핑크메이트', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('02. 골드 프리즘', '골드', 'pending_review', 'seed_llm_assignment', 1),
    ('023 베이비밀크냥냥', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('025 서울스칼렛', NULL, 'rejected', 'human', 1),
    ('03 복숭아진주', NULL, 'rejected', 'human', 2),
    ('03 탠 크러시', NULL, 'rejected', 'human', 1),
    ('03 피크닉레드', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('03. 핑크 프리즘', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('031 스트로베리', NULL, 'rejected', 'human', 1),
    ('033 코랄 핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('04 레드시그널', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('04 레몬별사탕', NULL, 'rejected', 'human', 2),
    ('04 비터 카라멜', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('04. 로제 프리즘', NULL, 'rejected', 'human', 1),
    ('05 솔티 피그', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('05 체리키스', NULL, 'rejected', 'human', 1),
    ('05. 코랄 프리즘', NULL, 'rejected', 'human', 1),
    ('06 너티 피치', NULL, 'rejected', 'human', 1),
    ('06. 라일락 프리즘', NULL, 'rejected', 'human', 1),
    ('07. 오로라 프리즘', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('10 로지 밤', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('13호 포슬린', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('1C0 쉘', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('1N0 포슬린', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('1N1 아이보리 누드', '아이보리', 'pending_review', 'seed_llm_assignment', 1),
    ('1W1 본', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('1W2 샌드', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('1그린', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('1호 애쉬 브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('20호 바닐라', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('21N1', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('21호', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('21호 내추럴 베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('21호 아이보리', '아이보리', 'pending_review', 'seed_llm_assignment', 1),
    ('22호 페탈', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('23N1', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('23N1 베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('23호', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('23호 베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('25호 탠', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('28 크리미 핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('2C0 쿨바닐라', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('2W0 웜바닐라', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('2옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('30 뮤트 로즈', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('31 피치 코랄', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('3W1 토니', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('3핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('3호 밀크 브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('42 로지 코랄', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('45 웜 레드', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('4푸시아핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('60 모브 플럼', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('6레드', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('BK', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('BR', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('CANDY FLUFF(NEW)', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('COOLEST', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('CR', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('Cherry Wood', '브라운', 'pending_review', 'seed_llm_assignment', 2),
    ('DarkGreyHeather/White', NULL, 'rejected', 'human', 1),
    ('Deep Brown', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('Grayish Cool', NULL, 'rejected', 'human', 1),
    ('LC5', NULL, 'rejected', 'human', 1),
    ('LN10', NULL, 'rejected', 'human', 1),
    ('LN25', NULL, 'rejected', 'human', 1),
    ('LN5', NULL, 'rejected', 'human', 1),
    ('LUZTIC', NULL, 'rejected', 'human', 1),
    ('MUTE LILAC(NEW)', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('Natural Brown', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('SPICED UP', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('TAN', '베이지', 'approved', 'human', 1),
    ('VERY SPRING(NEW)', NULL, 'rejected', 'human', 1),
    ('WT', NULL, 'rejected', 'human', 1),
    ('Walnut', '브라운', 'approved', 'human', 3),
    ('YAY OR NAY', NULL, 'rejected', 'human', 1),
    ('갈색', '브라운', 'approved', 'human', 2),
    ('건메탈', '그레이', 'approved', 'human', 1),
    ('검정', '블랙', 'approved', 'human', 11),
    ('검정색', '블랙', 'approved', 'human', 3),
    ('검회색', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('곤색', '네이비', 'approved', 'human', 5),
    ('골드', '골드', 'approved', 'human', 92),
    ('골드-블랙', '골드', 'pending_review', 'seed_llm_assignment', 1),
    ('골드-블루', '골드', 'pending_review', 'seed_llm_assignment', 1),
    ('골드-화이트', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('골드블랙', '골드', 'pending_review', 'seed_llm_assignment', 1),
    ('광택 검정 탄소 섬유', NULL, 'rejected', 'human', 1),
    ('광택 은색 노란색', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('광택 은색 마젠타', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('광택 은색 연한 파란색 LED', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('광택 은색 오렌지', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('광택 은색 카키 LED', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('광택 은회색 LED', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('광택 짙은 파란색', NULL, 'rejected', 'human', 1),
    ('광택 흰색 탄소 섬유', NULL, 'rejected', 'human', 1),
    ('광택 흰색 탄소 섬유 LED', NULL, 'rejected', 'human', 1),
    ('구아바', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('구형 플라스틱 원형', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('그라데이션블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('그레이', '그레이', 'approved', 'human', 750),
    ('그레이(카키)', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('그레이/네이비', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('그레이/실버', '그레이', 'pending_review', 'seed_llm_assignment', 11),
    ('그레이네이비', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('그레이브라운', '다크브라운', 'pending_review', 'seed_llm_assignment', 2),
    ('그레이블랙', '블랙', 'pending_review', 'seed_llm_assignment', 2),
    ('그레이블루', '그레이', 'pending_review', 'seed_llm_assignment', 4),
    ('그레이시블루', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('그레이오렌지', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('그레이지', '그레이', 'pending_review', 'seed_llm_assignment', 2),
    ('그레이청', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('그리너리', '그린', 'approved', 'human', 1),
    ('그린', '그린', 'approved', 'human', 287),
    ('글로시 실버 카키', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('글로시 은회색', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('금색', '골드', 'approved', 'human', 1),
    ('기타', NULL, 'pending_review', 'seed_llm_assignment', 70),
    ('꼬냑 스웨이드', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('꽃그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('꽃블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('꽃아이보리', '아이보리', 'pending_review', 'seed_llm_assignment', 1),
    ('꽃핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('남보라', '퍼플', 'pending_review', 'seed_llm_assignment', 2),
    ('남색', '네이비', 'approved', 'human', 8),
    ('내추럴', '베이지', 'pending_review', 'seed_llm_assignment', 2),
    ('내추럴 베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('내추럴 화이트', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('내추럴/우드', '베이지', 'pending_review', 'seed_llm_assignment', 2),
    ('내추럴베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('내추럴브라운', '브라운', 'pending_review', 'seed_llm_assignment', 5),
    ('내추럴블랙', '블랙', 'pending_review', 'seed_llm_assignment', 7),
    ('내추럴오크', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('내추럴우드', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('내츄럴브라운(자연갈색)', '브라운', 'pending_review', 'seed_llm_assignment', 5),
    ('네온로즈', '로즈골드', 'pending_review', 'seed_llm_assignment', 1),
    ('네이비', '네이비', 'approved', 'human', 632),
    ('네이비/블루', '네이비', 'pending_review', 'seed_llm_assignment', 1),
    ('네이비/청록', '네이비', 'pending_review', 'seed_llm_assignment', 1),
    ('네이비/카키', '네이비', 'pending_review', 'seed_llm_assignment', 1),
    ('네이비스트라이프', '네이비', 'pending_review', 'seed_llm_assignment', 2),
    ('네추럴', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('노란색', '옐로우', 'approved', 'human', 2),
    ('노랑', '옐로우', 'approved', 'human', 12),
    ('노랑색', '옐로우', 'approved', 'human', 3),
    ('노블 베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('녹색', '그린', 'approved', 'human', 4),
    ('녹색천', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('누드', NULL, 'pending_review', 'seed_llm_assignment', 17),
    ('누드/베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('누드베이지', '베이지', 'pending_review', 'seed_llm_assignment', 7),
    ('뉴그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('니켈/코퍼', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('다크그레이', '다크그레이', 'pending_review', 'seed_llm_assignment', 26),
    ('다크그린', '그린', 'pending_review', 'seed_llm_assignment', 22),
    ('다크네이비', '네이비', 'pending_review', 'seed_llm_assignment', 18),
    ('다크레드', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('다크모스', '다크그레이', 'pending_review', 'seed_llm_assignment', 4),
    ('다크민트', '민트', 'pending_review', 'seed_llm_assignment', 1),
    ('다크베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('다크브라운', '다크브라운', 'pending_review', 'seed_llm_assignment', 34),
    ('다크브라운(흑갈색)', '다크브라운', 'pending_review', 'seed_llm_assignment', 4),
    ('다크블루', '블루', 'pending_review', 'seed_llm_assignment', 9),
    ('다크블루(진청)', '네이비', 'pending_review', 'seed_llm_assignment', 6),
    ('다크실버', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('다크오렌지', '오렌지', 'pending_review', 'seed_llm_assignment', 1),
    ('다크차콜', '차콜', 'pending_review', 'seed_llm_assignment', 2),
    ('다크카키', '카키', 'pending_review', 'seed_llm_assignment', 1),
    ('다크핑크', '핑크', 'pending_review', 'seed_llm_assignment', 2),
    ('다홍색', '레드', 'pending_review', 'seed_llm_assignment', 2),
    ('단일색(호수 없음)', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('단일색상', NULL, 'pending_review', 'seed_llm_assignment', 10),
    ('담뱃재', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('더스티민트', '민트', 'pending_review', 'seed_llm_assignment', 3),
    ('더스티핑크', '핑크', 'pending_review', 'seed_llm_assignment', 3),
    ('데님', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('데님블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('도형블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('도형옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('듄카키', '카키', 'pending_review', 'seed_llm_assignment', 1),
    ('딥그레이', '다크그레이', 'pending_review', 'seed_llm_assignment', 2)
ON CONFLICT (term) DO UPDATE SET
    canonical = EXCLUDED.canonical,
    status = EXCLUDED.status,
    provenance = EXCLUDED.provenance,
    doc_count = EXCLUDED.doc_count;

INSERT INTO color_synonyms (term, canonical, status, provenance, doc_count) VALUES
    ('딥그린', '그린', 'pending_review', 'seed_llm_assignment', 9),
    ('딥네이비', '네이비', 'pending_review', 'seed_llm_assignment', 4),
    ('딥바이올렛', '퍼플', 'pending_review', 'seed_llm_assignment', 1),
    ('딥베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('딥브라운', '다크브라운', 'pending_review', 'seed_llm_assignment', 2),
    ('딥블랙', '블랙', 'pending_review', 'seed_llm_assignment', 4),
    ('딥블루', '블루', 'pending_review', 'seed_llm_assignment', 4),
    ('딥퍼플', '퍼플', 'pending_review', 'seed_llm_assignment', 2),
    ('라벤더', '라벤더', 'pending_review', 'seed_llm_assignment', 34),
    ('라벤더퍼플', '퍼플', 'pending_review', 'seed_llm_assignment', 1),
    ('라이트', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('라이트 그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('라이트 베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('라이트 블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('라이트그레이', '라이트그레이', 'pending_review', 'seed_llm_assignment', 32),
    ('라이트그린', '그린', 'pending_review', 'seed_llm_assignment', 9),
    ('라이트민트', '민트', 'pending_review', 'seed_llm_assignment', 1),
    ('라이트베이지', '베이지', 'pending_review', 'seed_llm_assignment', 9),
    ('라이트브라운', '브라운', 'pending_review', 'seed_llm_assignment', 15),
    ('라이트블루', '라이트블루', 'pending_review', 'seed_llm_assignment', 46),
    ('라이트블루(연청)', '스카이블루', 'pending_review', 'seed_llm_assignment', 10),
    ('라이트실버', '실버', 'pending_review', 'seed_llm_assignment', 4),
    ('라이트인디고', '인디고', 'pending_review', 'seed_llm_assignment', 11),
    ('라이트카키', '카키', 'pending_review', 'seed_llm_assignment', 2),
    ('라이트퍼플', '퍼플', 'pending_review', 'seed_llm_assignment', 1),
    ('라이트핑크', '핑크', 'pending_review', 'seed_llm_assignment', 4),
    ('라이트하바나', '베이지', 'pending_review', 'seed_llm_assignment', 2),
    ('라이트헤더그레이', '라이트그레이', 'pending_review', 'seed_llm_assignment', 3),
    ('라인그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('라일락', '퍼플', 'approved', 'human', 2),
    ('라임', '그린', 'pending_review', 'seed_llm_assignment', 4),
    ('라탄색', '베이지', 'approved', 'human', 1),
    ('랜덤', NULL, 'pending_review', 'seed_llm_assignment', 6),
    ('랜덤발송', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('랜덤컬러', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('레드', '레드', 'approved', 'human', 209),
    ('레드골드', '골드', 'pending_review', 'seed_llm_assignment', 1),
    ('레드와인', '와인', 'pending_review', 'seed_llm_assignment', 1),
    ('레몬', '옐로우', 'pending_review', 'seed_llm_assignment', 4),
    ('레오파드', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('레오파드골드', '골드', 'pending_review', 'seed_llm_assignment', 1),
    ('레인보우', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('로봇화이트', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('로얄블루', '블루', 'pending_review', 'seed_llm_assignment', 2),
    ('로열블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('로잘린핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('로즈', '핑크', 'approved', 'human', 7),
    ('로즈 톤업 밤 웜', NULL, 'rejected', 'human', 1),
    ('로즈 톤업 밤 쿨', NULL, 'rejected', 'human', 1),
    ('로즈골드', '로즈골드', 'pending_review', 'seed_llm_assignment', 28),
    ('로즈골드-블랙', '골드', 'pending_review', 'seed_llm_assignment', 1),
    ('로즈베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('로지 프로미스', NULL, 'rejected', 'human', 1),
    ('로지모브(더스티 핑크)', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('로지브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('루비레드', '레드', 'pending_review', 'seed_llm_assignment', 2),
    ('리얼블랙', '블랙', 'pending_review', 'seed_llm_assignment', 2),
    ('마린블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('마브 라벤더', '라벤더', 'pending_review', 'seed_llm_assignment', 1),
    ('마블 그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('마젠타', '핑크', 'pending_review', 'seed_llm_assignment', 3),
    ('말차그린', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('매트블랙', '블랙', 'pending_review', 'seed_llm_assignment', 4),
    ('매트화이트', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('머스타드', '옐로우', 'pending_review', 'seed_llm_assignment', 2),
    ('머스터드그린', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('멀티', NULL, 'pending_review', 'seed_llm_assignment', 15),
    ('멀티(리버서블)', NULL, 'pending_review', 'seed_llm_assignment', 20),
    ('멀티(스트라이프)', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('멀티(체크)', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('멀티(투톤)', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('멀티(패턴)', NULL, 'pending_review', 'seed_llm_assignment', 6),
    ('멀티(혼합)', NULL, 'pending_review', 'seed_llm_assignment', 20),
    ('멀티/기타', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('멀티/레오파드', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('멀티/스트라이프', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('멀티/프린트', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('멀티/혼합', NULL, 'pending_review', 'seed_llm_assignment', 11),
    ('멀티컬러', NULL, 'pending_review', 'seed_llm_assignment', 40),
    ('멀티팝', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('메탈 그레이', '그레이', 'pending_review', 'seed_llm_assignment', 2),
    ('메탈 블랙', '블랙', 'pending_review', 'seed_llm_assignment', 3),
    ('멜란지', '그레이', 'pending_review', 'seed_llm_assignment', 3),
    ('멜란지그레이', '그레이', 'pending_review', 'seed_llm_assignment', 17),
    ('멜란지핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('멜란지화이트', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('모닝 듀', NULL, 'rejected', 'human', 1),
    ('모던체크 그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('모카', '브라운', 'approved', 'human', 5),
    ('모카브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('모카스킨', '브라운', 'pending_review', 'seed_llm_assignment', 4),
    ('모카토프', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('무광 위장', NULL, 'rejected', 'human', 1),
    ('무광 위장 줄무늬 LED', NULL, 'rejected', 'human', 1),
    ('무지', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('뮤추얼 필링', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('뮤트 그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('미네랄 그레이.', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('미드나이트', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('미드나잇 네이비', '네이비', 'pending_review', 'seed_llm_assignment', 1),
    ('미드나잇블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('미드헤더그레이', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('미디엄브라운', '브라운', 'pending_review', 'seed_llm_assignment', 3),
    ('미디엄블루(중청)', '블루', 'pending_review', 'seed_llm_assignment', 6),
    ('미색', '베이지', 'approved', 'human', 2),
    ('미색화이트', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('믹스(혼합)', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('믹스드 베리', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('믹스컬러', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('민트', '민트', 'pending_review', 'seed_llm_assignment', 61),
    ('민트그린', '민트', 'pending_review', 'seed_llm_assignment', 3),
    ('민트네이비', '민트', 'pending_review', 'seed_llm_assignment', 1),
    ('민트블루', '민트', 'pending_review', 'seed_llm_assignment', 2),
    ('밀리터리', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('밀리터리그린', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('밀키베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('밀키블루', '블루', 'pending_review', 'seed_llm_assignment', 2),
    ('바닐라', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('바닐라 너츠', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('바닐라베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('바다그린색', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('바이올렛', '퍼플', 'approved', 'human', 8),
    ('바이올렛(84)', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('반짝이는 로즈 핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('반투명', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('밝은 은록색', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('밝은 은색주황 LED', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('밝은 은황색 LED', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('밝은 하늘색', '스카이블루', 'pending_review', 'seed_llm_assignment', 1),
    ('밝은핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('백색', '화이트', 'approved', 'human', 5),
    ('백색(흰색)', '화이트', 'approved', 'human', 2),
    ('버건디', '와인', 'approved', 'human', 16),
    ('버터옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 2),
    ('버터크림', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('베네통그린', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('베라블랙', '블랙', 'pending_review', 'seed_llm_assignment', 3),
    ('베리', '레드', 'pending_review', 'seed_llm_assignment', 2),
    ('베리핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('베쉬', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('베이비핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('베이지', '베이지', 'approved', 'human', 592),
    ('베이지/스킨톤', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('베이지핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('베이직', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('보라', '퍼플', 'approved', 'human', 17),
    ('보라(84)', NULL, 'rejected', 'human', 1),
    ('보라색', '퍼플', 'approved', 'human', 3),
    ('보람천', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('보람포', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('본', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('분홍', '핑크', 'approved', 'human', 1),
    ('붉은색', '레드', 'approved', 'human', 1),
    ('브라운', '브라운', 'approved', 'human', 401),
    ('브라운/갈색', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('브라운카키', '카키', 'pending_review', 'seed_llm_assignment', 1),
    ('브란스', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('브릭', '브라운', 'pending_review', 'seed_llm_assignment', 3),
    ('블랙', '블랙', 'approved', 'human', 2358),
    ('블랙 머스크', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙+브라운(혼합)', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙-블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙/로즈골드', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙/브라운(양면)', NULL, 'pending_review', 'seed_llm_assignment', 10),
    ('블랙/화이트', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('블랙2', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙골드', '골드', 'pending_review', 'seed_llm_assignment', 2),
    ('블랙그린', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙네이비', '네이비', 'pending_review', 'seed_llm_assignment', 8),
    ('블랙누아르', '블랙', 'pending_review', 'seed_llm_assignment', 3),
    ('블랙브라운', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙실버', '실버', 'pending_review', 'seed_llm_assignment', 2),
    ('블랙차콜', '차콜', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙청', '블루', 'pending_review', 'seed_llm_assignment', 2),
    ('블랙펄', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('블랙화이트', '블랙', 'pending_review', 'seed_llm_assignment', 3),
    ('블러쉬베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('블루', '블루', 'approved', 'human', 438),
    ('블루 머스크', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('블루 머스크 제스트', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('블루(73)', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('블루(청록)', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('블루(하늘색)', '스카이', 'pending_review', 'seed_llm_assignment', 1),
    ('블루그레이', '블루', 'pending_review', 'seed_llm_assignment', 3),
    ('블루그린', '그린', 'pending_review', 'seed_llm_assignment', 3),
    ('블루바이올렛', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('블루블루', '블루', 'pending_review', 'seed_llm_assignment', 2),
    ('블루청', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('블루화이트', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('비비드라이트블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('비비드블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('비비드옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('비비드오렌지', '오렌지', 'pending_review', 'seed_llm_assignment', 1),
    ('비비드핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('빈티지', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('빈티지블루', '블루', 'pending_review', 'seed_llm_assignment', 7),
    ('빛나는 라이트 블루', '라이트블루', 'pending_review', 'seed_llm_assignment', 1),
    ('빛나는 붉은색', '레드', 'pending_review', 'seed_llm_assignment', 1)
ON CONFLICT (term) DO UPDATE SET
    canonical = EXCLUDED.canonical,
    status = EXCLUDED.status,
    provenance = EXCLUDED.provenance,
    doc_count = EXCLUDED.doc_count;

INSERT INTO color_synonyms (term, canonical, status, provenance, doc_count) VALUES
    ('빨강', '레드', 'approved', 'human', 7),
    ('빨강색', '레드', 'approved', 'human', 3),
    ('살구', '오렌지', 'pending_review', 'seed_llm_assignment', 2),
    ('살구색', '핑크', 'approved', 'human', 13),
    ('살색', NULL, 'pending_review', 'seed_llm_assignment', 5),
    ('상세설명참조', NULL, 'pending_review', 'seed_llm_assignment', 5),
    ('상세페이지 참조', NULL, 'pending_review', 'seed_llm_assignment', 4),
    ('새틴 그레이지', '그레이', 'pending_review', 'seed_llm_assignment', 2),
    ('새틴 베이지', '베이지', 'pending_review', 'seed_llm_assignment', 2),
    ('샌드', '베이지', 'approved', 'human', 2),
    ('샌드 화이트', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('샌드베이지', '베이지', 'pending_review', 'seed_llm_assignment', 2),
    ('샌드브라운', '브라운', 'pending_review', 'seed_llm_assignment', 2),
    ('샌드스톤', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('샌드스톰', '차콜', 'pending_review', 'seed_llm_assignment', 1),
    ('생지', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('샤이니 구스 옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('샤이니 올리브', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('샴페인', '아이보리', 'pending_review', 'seed_llm_assignment', 1),
    ('세라믹핑크/로즈골드', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('세이지', '베이지', 'pending_review', 'seed_llm_assignment', 3),
    ('세틴그레이지', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('소라', '스카이블루', 'approved', 'human', 6),
    ('소프트그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('소프트베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('소프트브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('소프트블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('솔리드블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('솝스톤 차콜', '차콜', 'pending_review', 'seed_llm_assignment', 2),
    ('스마일네이비', '네이비', 'pending_review', 'seed_llm_assignment', 1),
    ('스마일옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('스카이', '스카이', 'pending_review', 'seed_llm_assignment', 27),
    ('스카이 블루', '스카이', 'pending_review', 'seed_llm_assignment', 1),
    ('스카이블루', '스카이블루', 'approved', 'human', 55),
    ('스킨', NULL, 'pending_review', 'seed_llm_assignment', 26),
    ('스킨/베이지', '베이지', 'pending_review', 'seed_llm_assignment', 3),
    ('스킨베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('스킨색', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('스타 그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('스타 블랙.', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('스타 실버', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('스타라이트', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('스타리 실버', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('스테인리스', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('스테인리스 스틸 링', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('스테인리스 스틸 원형+AATCC 콘트라스트 카드', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('스텔라', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('스톤', '그레이', 'approved', 'human', 2),
    ('스트라이프', NULL, 'pending_review', 'seed_llm_assignment', 4),
    ('시에나브라운', '브라운', 'pending_review', 'seed_llm_assignment', 2),
    ('시에라블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('시크 블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('시티레드', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('실버', '실버', 'approved', 'human', 250),
    ('실버 그레이', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('실버(은색)', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('실버+블랙', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('실버/홀로그램', '실버', 'pending_review', 'seed_llm_assignment', 2),
    ('실버블랙', '실버', 'pending_review', 'seed_llm_assignment', 3),
    ('실버블루', '실버', 'pending_review', 'seed_llm_assignment', 3),
    ('썸머베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('썸머브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('아몬드그린', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('아몬드오렌지', '오렌지', 'pending_review', 'seed_llm_assignment', 1),
    ('아보카도', '그린', 'approved', 'human', 1),
    ('아이보리', '아이보리', 'pending_review', 'seed_llm_assignment', 223),
    ('아이보리/퍼플', '아이보리', 'pending_review', 'seed_llm_assignment', 1),
    ('아이보리그레이', '아이보리', 'pending_review', 'seed_llm_assignment', 1),
    ('아이보리색', '아이보리', 'pending_review', 'seed_llm_assignment', 1),
    ('아이스 오펄', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('아이스블루', '블루', 'pending_review', 'seed_llm_assignment', 3),
    ('아이스셀', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('아이스오펄', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('아이언 레드', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('아카시아', '그린', 'pending_review', 'seed_llm_assignment', 2),
    ('아쿠아', '블루', 'pending_review', 'seed_llm_assignment', 3),
    ('아프리칸 바이올렛', '퍼플', 'approved', 'human', 1),
    ('애쉬', '그레이', 'approved', 'human', 2),
    ('애쉬그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('애쉬브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('애쉬블루', '블루', 'pending_review', 'seed_llm_assignment', 2),
    ('애쉬청', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('애쉬핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('앤틱그린', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('에어블랙', '블랙', 'pending_review', 'seed_llm_assignment', 2),
    ('에어블루', '블루', 'pending_review', 'seed_llm_assignment', 2),
    ('에어크림', '크림', 'pending_review', 'seed_llm_assignment', 2),
    ('에크루', '크림', 'approved', 'human', 1),
    ('에토프', NULL, 'pending_review', 'seed_llm_assignment', 9),
    ('에토프 실버', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('에토프실버', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('엔틱', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('엔틱골드', '골드', 'pending_review', 'seed_llm_assignment', 4),
    ('엠버 옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('연갈색', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('연그레이', NULL, 'pending_review', 'seed_llm_assignment', 4),
    ('연그린', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('연노랑', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('연두', '그린', 'pending_review', 'seed_llm_assignment', 4),
    ('연두색', '그린', 'pending_review', 'seed_llm_assignment', 4),
    ('연베이지', '베이지', 'pending_review', 'seed_llm_assignment', 3),
    ('연보라', '퍼플', 'pending_review', 'seed_llm_assignment', 2),
    ('연보라색', '퍼플', 'pending_review', 'seed_llm_assignment', 3),
    ('연분홍', '핑크', 'pending_review', 'seed_llm_assignment', 6),
    ('연브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('연블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('연살구색', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('연지', '레드', 'approved', 'human', 1),
    ('연청', '블루', 'pending_review', 'seed_llm_assignment', 8),
    ('연청색천', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('연커피색', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('연핑크', '핑크', 'pending_review', 'seed_llm_assignment', 10),
    ('연핑크(16)', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('연하늘', '스카이', 'pending_review', 'seed_llm_assignment', 1),
    ('연회색', '그레이', 'pending_review', 'seed_llm_assignment', 2),
    ('연회색.', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('옐로', '옐로우', 'approved', 'human', 4),
    ('옐로우', '옐로우', 'approved', 'human', 160),
    ('옐로우골드', '골드', 'pending_review', 'seed_llm_assignment', 5),
    ('옐로우블랙', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('오닉스 블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('오렌지', '오렌지', 'approved', 'human', 88),
    ('오렌지그레이', '오렌지', 'pending_review', 'seed_llm_assignment', 1),
    ('오렌지색', '오렌지', 'pending_review', 'seed_llm_assignment', 3),
    ('오션블루', '블루', 'pending_review', 'seed_llm_assignment', 4),
    ('오크', '브라운', 'pending_review', 'seed_llm_assignment', 4),
    ('오트밀', '크림', 'pending_review', 'seed_llm_assignment', 5),
    ('오트밀멜란지', '크림', 'pending_review', 'seed_llm_assignment', 4),
    ('오트베이지', '베이지', 'pending_review', 'seed_llm_assignment', 2),
    ('오프화이트', '화이트', 'pending_review', 'seed_llm_assignment', 8),
    ('올골드', '골드', 'pending_review', 'seed_llm_assignment', 1),
    ('올리브', '그린', 'pending_review', 'seed_llm_assignment', 19),
    ('올리브그린', '그린', 'pending_review', 'seed_llm_assignment', 11),
    ('올리브카키', '카키', 'pending_review', 'seed_llm_assignment', 1),
    ('올블랙', '블랙', 'pending_review', 'seed_llm_assignment', 4),
    ('와인', '와인', 'approved', 'human', 35),
    ('와인브라운(적갈색)', '와인', 'pending_review', 'seed_llm_assignment', 2),
    ('우드', NULL, 'pending_review', 'seed_llm_assignment', 6),
    ('우드/원목색', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('우드톤', '브라운', 'pending_review', 'seed_llm_assignment', 4),
    ('워싱블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('원목색', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('월넛', '브라운', 'approved', 'human', 5),
    ('월넛 베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('월넛 화이트', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('웜그레이', '다크그레이', 'pending_review', 'seed_llm_assignment', 3),
    ('유광 실버 로즈 핑크 LED', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('은색', '실버', 'approved', 'human', 1),
    ('인디고', '인디고', 'pending_review', 'seed_llm_assignment', 34),
    ('인디네이비', '네이비', 'pending_review', 'seed_llm_assignment', 1),
    ('인디블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('인디핑크', '핑크', 'pending_review', 'seed_llm_assignment', 4),
    ('일반(황색/미표기)', NULL, 'rejected', 'human', 6),
    ('잉크', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('잉크블랙', '블랙', 'pending_review', 'seed_llm_assignment', 2),
    ('자색/보라색', '퍼플', 'approved', 'human', 1),
    ('자연갈색', '브라운', 'pending_review', 'seed_llm_assignment', 2),
    ('자연검정', '블랙', 'pending_review', 'seed_llm_assignment', 3),
    ('자주', '퍼플', 'approved', 'human', 1),
    ('자카드 교토', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('자카드 라이트 레오파드', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('자카드 파스텔 꽃', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('제트 블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('제트블랙', '블랙', 'pending_review', 'seed_llm_assignment', 3),
    ('젯블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('주차금지', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('주황', '오렌지', 'approved', 'human', 3),
    ('줄보라', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('중청', '블루', 'pending_review', 'seed_llm_assignment', 10),
    ('쥐색', '그레이', 'approved', 'human', 1),
    ('쥬스한잔', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('지그재그', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('지그재그 그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('진그레이', '다크그레이', 'pending_review', 'seed_llm_assignment', 3),
    ('진그레이오렌지', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('진노랑', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('진밤', '브라운', 'pending_review', 'seed_llm_assignment', 2),
    ('진분홍', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('진브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('진블루', '블루', 'pending_review', 'seed_llm_assignment', 2),
    ('진저', '오렌지', 'pending_review', 'seed_llm_assignment', 1),
    ('진청', '다크그레이', 'pending_review', 'seed_llm_assignment', 9),
    ('진한갈색', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('진회색', '그레이', 'pending_review', 'seed_llm_assignment', 3),
    ('짙은갈색', '브라운', 'pending_review', 'seed_llm_assignment', 2),
    ('짙은회색', '다크그레이', 'pending_review', 'seed_llm_assignment', 2),
    ('차분한베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('차콜', '차콜', 'approved', 'human', 72),
    ('차콜 그레이', '차콜', 'pending_review', 'seed_llm_assignment', 1),
    ('차콜그레이', '차콜', 'pending_review', 'seed_llm_assignment', 1),
    ('챠콜', '차콜', 'approved', 'human', 1),
    ('철회색천', '그레이', 'approved', 'human', 1),
    ('청녹색', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('청록', '스카이블루', 'pending_review', 'seed_llm_assignment', 5),
    ('청록/블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('청록/카키', '카키', 'pending_review', 'seed_llm_assignment', 1),
    ('청색', '블루', 'approved', 'human', 2),
    ('체리로즈', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('체리블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('체크', NULL, 'pending_review', 'seed_llm_assignment', 1)
ON CONFLICT (term) DO UPDATE SET
    canonical = EXCLUDED.canonical,
    status = EXCLUDED.status,
    provenance = EXCLUDED.provenance,
    doc_count = EXCLUDED.doc_count;

INSERT INTO color_synonyms (term, canonical, status, provenance, doc_count) VALUES
    ('체크그린', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('체크네이비', '네이비', 'pending_review', 'seed_llm_assignment', 1),
    ('체크블랙', '블랙', 'pending_review', 'seed_llm_assignment', 2),
    ('체크스카이', '스카이블루', 'pending_review', 'seed_llm_assignment', 1),
    ('초록', '그린', 'approved', 'human', 1),
    ('초록색', '그린', 'approved', 'human', 1),
    ('초코브라운', '브라운', 'pending_review', 'seed_llm_assignment', 7),
    ('초크화이트', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('칠리레드', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('카라멜', '브라운', 'approved', 'human', 2),
    ('카멜', '브라운', 'approved', 'human', 14),
    ('카멜브라운', '브라운', 'pending_review', 'seed_llm_assignment', 3),
    ('카모', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('카모/카키카모', '카키', 'pending_review', 'seed_llm_assignment', 1),
    ('카본블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('카카오브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('카키', '카키', 'pending_review', 'seed_llm_assignment', 196),
    ('카키/블루', '카키', 'pending_review', 'seed_llm_assignment', 1),
    ('카키가죽', '카키', 'pending_review', 'seed_llm_assignment', 1),
    ('카키그레이', '카키', 'pending_review', 'seed_llm_assignment', 1),
    ('카키브라운', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('카키색', '카키', 'pending_review', 'seed_llm_assignment', 3),
    ('카키포리지', '카키', 'pending_review', 'seed_llm_assignment', 1),
    ('카페오레', '베이지', 'approved', 'human', 1),
    ('캐시미어', '아이보리', 'pending_review', 'seed_llm_assignment', 1),
    ('커스타드 옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('커스터드 옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('커피', '브라운', 'approved', 'human', 8),
    ('커피 그라운드', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('커피/브라운', '브라운', 'pending_review', 'seed_llm_assignment', 2),
    ('커피색', '브라운', 'approved', 'human', 2),
    ('컬러', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('컬러4종', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('코냑', '브라운', 'approved', 'human', 1),
    ('코랄', '핑크', 'pending_review', 'seed_llm_assignment', 4),
    ('코랄레드', '레드', 'pending_review', 'seed_llm_assignment', 2),
    ('코발트', '블루', 'approved', 'human', 2),
    ('코발트 바이올렛', '퍼플', 'pending_review', 'seed_llm_assignment', 2),
    ('코발트블루', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('코스탈블루', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('코코넛베이지', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('코코아', '브라운', 'approved', 'human', 2),
    ('코튼 핑크', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('콜그레이', '그레이', 'pending_review', 'seed_llm_assignment', 3),
    ('쿨그레이', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('크롬', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('크롬/실버', '실버', 'pending_review', 'seed_llm_assignment', 3),
    ('크리스탈베이지', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('크림', '크림', 'approved', 'human', 50),
    ('크림골드', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('크림로즈', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('크림베이지', '베이지', 'pending_review', 'seed_llm_assignment', 6),
    ('크림아이보리', '아이보리', 'pending_review', 'seed_llm_assignment', 2),
    ('크림화이트', '화이트', 'pending_review', 'seed_llm_assignment', 6),
    ('클라우드', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('클래식그린', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('클래식블루', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('클래식옐로우', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('클래식오렌지', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('클리어', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('클리어베이지', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('클리어브라운', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('클리어블루', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('탄', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('터콰이즈그린', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('터키블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('토파즈', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('토프', '브라운', 'pending_review', 'seed_llm_assignment', 3),
    ('투명', NULL, 'pending_review', 'seed_llm_assignment', 45),
    ('투명 실버', '실버', 'pending_review', 'seed_llm_assignment', 1),
    ('투명/무색', NULL, 'pending_review', 'seed_llm_assignment', 10),
    ('투명/반투명', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('투명/크리스탈', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('투명그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('투명레드', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('투명블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('투톤', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('특허 워터프루프 디자인++AATCC 콘트라스트 카드', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('특허 집수 설계', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('티아라 핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('티크', '브라운', 'approved', 'human', 1),
    ('티타늄', NULL, 'pending_review', 'seed_llm_assignment', 9),
    ('틸블루', '블루', 'pending_review', 'seed_llm_assignment', 5),
    ('파랑', '블루', 'approved', 'human', 4),
    ('파랑색', '블루', 'approved', 'human', 5),
    ('파스텔 옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('파스텔노랑', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('파스텔보라', '퍼플', 'pending_review', 'seed_llm_assignment', 1),
    ('파스텔블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('파스텔혼합', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('파우더베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('패브릭 블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('패턴/캐릭터', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('퍼플', '퍼플', 'approved', 'human', 130),
    ('퍼플/보라', '퍼플', 'pending_review', 'seed_llm_assignment', 11),
    ('퍼플그레이', '퍼플', 'pending_review', 'seed_llm_assignment', 1),
    ('퍼플라벤더', '퍼플', 'pending_review', 'seed_llm_assignment', 1),
    ('펀칭블랙', '블랙', 'pending_review', 'seed_llm_assignment', 5),
    ('펄', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('펄그레이', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('펄레드', '레드', 'pending_review', 'seed_llm_assignment', 1),
    ('펄블랙', '블랙', 'pending_review', 'seed_llm_assignment', 1),
    ('펄차콜', '차콜', 'pending_review', 'seed_llm_assignment', 1),
    ('펄화이트', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('페일블루', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('페일코발트', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('페탈', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('페트롤블루', '블루', 'pending_review', 'seed_llm_assignment', 4),
    ('포슬린', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('포인트', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('포인트핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('폴리스네이비', '네이비', 'pending_review', 'seed_llm_assignment', 1),
    ('표기없음', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('푸시아 핑크', '핑크', 'pending_review', 'seed_llm_assignment', 3),
    ('푸시아핑크', '핑크', 'pending_review', 'seed_llm_assignment', 3),
    ('퓨어 그레이.', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('프레쉬민트', '민트', 'pending_review', 'seed_llm_assignment', 1),
    ('프레스코', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('프로즌크리스탈', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('플라스틱 원형', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('플라스틱 원형+AATCC 콘트라스트 카드', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('플라워', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('플라워네이비', '네이비', 'pending_review', 'seed_llm_assignment', 1),
    ('플라워다크', NULL, 'rejected', 'human', 1),
    ('플라워블랙', '블랙', 'pending_review', 'seed_llm_assignment', 4),
    ('플럼', '퍼플', 'approved', 'human', 3),
    ('플럼 스모크', '퍼플', 'pending_review', 'seed_llm_assignment', 1),
    ('피스타치오그린', '그린', 'pending_review', 'seed_llm_assignment', 2),
    ('피치', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('피치베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('피치사파이어', '블루', 'pending_review', 'seed_llm_assignment', 1),
    ('피치스킨', '오렌지', 'pending_review', 'seed_llm_assignment', 4),
    ('피치핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('핑크', '핑크', 'approved', 'human', 381),
    ('핑크골드', '골드', 'pending_review', 'seed_llm_assignment', 4),
    ('핑크골드(로즈골드)', '골드', 'pending_review', 'seed_llm_assignment', 1),
    ('핑크베이지', '핑크', 'pending_review', 'seed_llm_assignment', 5),
    ('핑크색', '핑크', 'pending_review', 'seed_llm_assignment', 5),
    ('하늘색', '스카이블루', 'approved', 'human', 10),
    ('하바나', '브라운', 'pending_review', 'seed_llm_assignment', 4),
    ('하얀색', '화이트', 'approved', 'human', 1),
    ('핫핑크', '핑크', 'pending_review', 'seed_llm_assignment', 4),
    ('해당없음', NULL, 'pending_review', 'seed_llm_assignment', 27),
    ('헌터그린', '그린', 'pending_review', 'seed_llm_assignment', 3),
    ('형광', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('형광그린', NULL, 'pending_review', 'seed_llm_assignment', 5),
    ('형광녹색', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('형광연두', '그린', 'pending_review', 'seed_llm_assignment', 1),
    ('호피', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('혼합', NULL, 'pending_review', 'seed_llm_assignment', 6),
    ('혼합(랜덤)', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('혼합(레드/옐로/화이트)', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('혼합(투톤)', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('혼합/기타', NULL, 'pending_review', 'seed_llm_assignment', 4),
    ('혼합/랜덤', NULL, 'pending_review', 'seed_llm_assignment', 5),
    ('혼합/멀티', NULL, 'pending_review', 'seed_llm_assignment', 16),
    ('혼합/상세설명참조', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('혼합/세트', NULL, 'pending_review', 'seed_llm_assignment', 3),
    ('혼합/투톤', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('혼합구성', NULL, 'pending_review', 'seed_llm_assignment', 2),
    ('혼합색', NULL, 'pending_review', 'seed_llm_assignment', 4),
    ('혼합색상', NULL, 'pending_review', 'seed_llm_assignment', 132),
    ('혼합색상(멀티)', NULL, 'pending_review', 'seed_llm_assignment', 9),
    ('혼합형', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('홍색/적색', '레드', 'approved', 'human', 1),
    ('화사한베이지', '베이지', 'pending_review', 'seed_llm_assignment', 1),
    ('화이트', '화이트', 'approved', 'human', 869),
    ('화이트 머스크 오리지널', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('화이트(하늘색 배색)', '화이트', 'pending_review', 'seed_llm_assignment', 1),
    ('화이트+네이비', '화이트', 'pending_review', 'seed_llm_assignment', 9),
    ('화이트/실버', '화이트', 'pending_review', 'seed_llm_assignment', 3),
    ('화이트골드', '골드', 'pending_review', 'seed_llm_assignment', 8),
    ('화이트크림', '화이트', 'pending_review', 'seed_llm_assignment', 2),
    ('황금', '골드', 'approved', 'human', 1),
    ('황금색(옐로우골드)', '골드', 'pending_review', 'seed_llm_assignment', 1),
    ('황색', '옐로우', 'approved', 'human', 1),
    ('황토색', NULL, 'pending_review', 'seed_llm_assignment', 1),
    ('회갈색', '브라운', 'pending_review', 'seed_llm_assignment', 1),
    ('회색', '그레이', 'approved', 'human', 5),
    ('회색가죽(대리석무늬)', '그레이', 'pending_review', 'seed_llm_assignment', 1),
    ('흑갈색', '블랙', 'pending_review', 'seed_llm_assignment', 2),
    ('흑색', '블랙', 'approved', 'human', 9),
    ('흑청', '블랙', 'pending_review', 'seed_llm_assignment', 5),
    ('흰둥이', '화이트', 'approved', 'human', 1),
    ('흰둥이블루', NULL, 'rejected', 'human', 1),
    ('흰둥이아이보리', '아이보리', 'pending_review', 'seed_llm_assignment', 1),
    ('흰둥이옐로우', '옐로우', 'pending_review', 'seed_llm_assignment', 1),
    ('흰둥이핑크', '핑크', 'pending_review', 'seed_llm_assignment', 1),
    ('흰색', '화이트', 'approved', 'human', 5)
ON CONFLICT (term) DO UPDATE SET
    canonical = EXCLUDED.canonical,
    status = EXCLUDED.status,
    provenance = EXCLUDED.provenance,
    doc_count = EXCLUDED.doc_count;
